package com.sharkitecture.sensory;

import java.util.ArrayList;
import java.util.List;

/**
 * Ampullae of Lorenzini — detects the weak electrical fields
 * generated by the muscle contractions of nearby organisms.
 * Unique to sharks and rays.
 */
public class Electroreception {

    private static final double DETECTION_RANGE_METERS = 1.5;
    private static final double SENSITIVITY_THRESHOLD = 0.005; // nanovolts per cm

    private final int ampullaeCount;

    public Electroreception(int ampullaeCount) {
        this.ampullaeCount = ampullaeCount;
    }

    public List<SensoryInput> scan(double[] electricalFieldReadings) {
        List<SensoryInput> detectedInputs = new ArrayList<>();

        for (int i = 0; i < electricalFieldReadings.length; i++) {
            double reading = electricalFieldReadings[i];
            if (reading >= SENSITIVITY_THRESHOLD) {
                double normalizedIntensity = Math.min(reading / 1.0, 1.0);
                double bearing = (360.0 / electricalFieldReadings.length) * i;
                detectedInputs.add(new SensoryInput(
                        SensoryInput.InputType.ELECTRICAL, normalizedIntensity, bearing));
            }
        }

        return detectedInputs;
    }

    public int getAmpullaeCount() {
        return ampullaeCount;
    }

    public double getDetectionRange() {
        return DETECTION_RANGE_METERS * (ampullaeCount / 1500.0);
    }
}
